/**
 * downloadLabelsSpreadsheet — generate an .xlsx with one row per item, for
 * NIIMBOT's own "Importar desde Excel" data-source flow (Fuente de datos →
 * Biblioteca de productos → Importar desde Excel). NIIMBOT merges this data
 * into a print template there — the QR itself is generated by NIIMBOT from
 * the URL column (its template editor supports a "QR code" field type bound
 * to a text column), not embedded as an image here.
 *
 * xlsx is dynamically imported so the (fairly large) library only loads when
 * an operator actually exports, not on every Fotosíntesis page load.
 */

const STUDIO_BASE_URL = 'https://tierramadre.app';
const LOGO_URL = `${STUDIO_BASE_URL}/logo-symbol.png`;

export interface SpreadsheetLabelItem {
  itemId: string;
  nombre?: string;
  peso?: string;
}

/**
 * Column headers are in Spanish, matching the app's locale and NIIMBOT's own
 * UI. `Logo` repeats the same static URL on every row — NIIMBOT's per-row
 * image-column binding (if the template uses one) needs a value in every
 * row; the label's logo is otherwise a fixed template element, not
 * per-item data.
 */
export async function downloadLabelsSpreadsheet(
  items: SpreadsheetLabelItem[],
  filename: string,
): Promise<void> {
  const XLSX = await import('xlsx');

  const rows = items.map((item) => ({
    Codigo: item.itemId,
    Nombre: item.nombre ?? '',
    Peso: item.peso ?? '',
    'Codigo QR': `${STUDIO_BASE_URL}/product/${item.itemId}`,
    Logo: LOGO_URL,
  }));

  const worksheet = XLSX.utils.json_to_sheet(rows);
  // Reasonable default column widths so the sheet is readable without the
  // operator manually resizing every column before mapping fields in NIIMBOT.
  worksheet['!cols'] = [
    { wch: 10 }, // Codigo
    { wch: 24 }, // Nombre
    { wch: 12 }, // Peso
    { wch: 42 }, // Codigo QR
    { wch: 42 }, // Logo
  ];

  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, 'Etiquetas');
  XLSX.writeFile(workbook, filename);
}
